language: php
php:
 - '7.0'
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install
  - mysql -e "CREATE DATABASE twitchbots"
script:
  - php -l public/index.php
  - php -l api/index.php
  - php vendor/bin/twig-lint lint Mini/view/
  - phpunit test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - source .travis/trust-server.sh
  - ssh humanoid@humanoids.be 'cd dev/twitchbots && git pull && php70 composer.phar install --no-dev --optimize-autoloader'
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    tags: true
    php: '7.0'
    repo: freaktechnik/twitchbots
